export const COMPONENT_INFO = {
  socket: {
    name: "CPU Socket",
    cat: "Processing",
    col: "#E8631A",
    desc: "The electro-mechanical interface connecting the processor to the board. Every signal — power, PCIe lanes, memory bus — passes through here.",
    specs: [
      ["AMD AM5", "1718 LGA pins on motherboard"],
      ["Intel LGA1851", "1851 contacts on board"],
      ["Bandwidth", "DDR5 + PCIe 5.0 + DMI 4.0"],
    ] as [string, string][],
    fact: "One AM5 socket carries over 200 GB/s of combined bandwidth through contacts thinner than a human hair.",
  },
  vrm: {
    name: "VRM",
    cat: "Power",
    col: "#CC8800",
    desc: "Voltage Regulator Module — converts 12V from the PSU to the precise low voltage the CPU needs (0.7–1.5V).",
    specs: [
      ["Input", "12V from PSU"],
      ["Output", "0.7–1.5V to CPU"],
      ["Phases", "6–24 on consumer boards"],
    ] as [string, string][],
    fact: "VRM coil whine is literally the inductor core vibrating at its 300kHz–2MHz switching frequency.",
  },
  dimm: {
    name: "DIMM Slots",
    cat: "Memory",
    col: "#1A9E65",
    desc: "Hold system RAM modules. Install in A2+B2 paired slots for dual-channel mode, doubling memory bandwidth.",
    specs: [
      ["DDR5", "288-pin, 4800–8400+ MT/s"],
      ["Dual-channel", "A2+B2 doubles bandwidth"],
      ["Max", "Up to 192 GB DDR5"],
    ] as [string, string][],
    fact: "Two 16 GB sticks is always faster than one 32 GB stick — dual-channel is free performance.",
  },
  pcie16: {
    name: "PCIe x16 Slot",
    cat: "Processing",
    col: "#E8631A",
    desc: "Primary GPU slot. 16 CPU-direct PCIe lanes. PCIe 5.0 = 128 GB/s. Metal clip locks GPU in place.",
    specs: [
      ["PCIe 5.0 x16", "128 GB/s bidirectional"],
      ["PCIe 4.0 x16", "64 GB/s bidirectional"],
    ] as [string, string][],
    fact: "PCIe is backwards compatible — a PCIe 3.0 GPU works in a PCIe 5.0 slot at Gen 3 speed.",
  },
  pch: {
    name: "PCH",
    cat: "Controller",
    col: "#4433AA",
    desc: "Platform Controller Hub. Manages USB, SATA, secondary PCIe, M.2 #2, and audio via DMI 4.0.",
    specs: [
      ["CPU link", "DMI 4.0 ≈ 16 GB/s total"],
      ["Manages", "USB, SATA, audio, PCIe x4/x1"],
    ] as [string, string][],
    fact: "All PCH-attached devices share its 16 GB/s DMI link simultaneously — a hidden shared bottleneck.",
  },
  atx24: {
    name: "24-pin ATX",
    cat: "Power",
    col: "#CC8800",
    desc: "Primary power from PSU. Delivers 3.3V, 5V, 12V, -12V rails. Keyed — impossible to insert backwards.",
    specs: [
      ["Voltages", "3.3V, 5V, 12V, -12V, 5VSB"],
      ["Capacity", "~264W across all rails"],
    ] as [string, string][],
    fact: "Pin 9 (+5VSB) stays live when the PC is off — enabling USB charging and Wake-on-LAN.",
  },
  sata: {
    name: "SATA Ports",
    cat: "Storage",
    col: "#0E70C0",
    desc: "Connect HDDs and 2.5-inch SATA SSDs. SATA III tops out at ~550 MB/s.",
    specs: [
      ["Speed", "~550 MB/s (SATA III)"],
      ["Ports", "4–8 typical"],
    ] as [string, string][],
    fact: "SATA ports can be angled right or straight — orientation matters for cable routing.",
  },
  bios: {
    name: "BIOS / UEFI ROM",
    cat: "Controller",
    col: "#4433AA",
    desc: "SPI NOR flash chip storing UEFI firmware. Initializes all hardware during POST.",
    specs: [
      ["Type", "SPI NOR Flash"],
      ["Capacity", "32–256 MB"],
    ] as [string, string][],
    fact: "Modern UEFI includes a full GUI, mouse, fan curves, XMP profiles, and sometimes AI overclocking.",
  },
  cmos: {
    name: "CMOS Battery",
    cat: "Misc",
    col: "#777777",
    desc: "CR2032 coin cell powering CMOS SRAM — stores BIOS settings when the PC is unplugged.",
    specs: [
      ["Type", "CR2032, 3V"],
      ["Lifespan", "5–10 years"],
    ] as [string, string][],
    fact: "Removing the CMOS battery resets all BIOS settings to defaults — the oldest troubleshooting trick.",
  },
  m2: {
    name: "M.2 Slot",
    cat: "Storage",
    col: "#0E70C0",
    desc: "CPU-direct NVMe slot. PCIe 4.0 = 7,000 MB/s, PCIe 5.0 = 14,000 MB/s. No cable needed.",
    specs: [
      ["PCIe 4.0 x4", "7,000 MB/s read"],
      ["PCIe 5.0 x4", "14,000 MB/s read"],
    ] as [string, string][],
    fact: "M.2 2280 = 22mm wide, 80mm long. Most NVMe SSDs use this form factor.",
  },
  cpu: {
    name: "CPU",
    cat: "Processing",
    col: "#E8631A",
    desc: "AMD Ryzen 9 7950X — 16 cores, 32 threads. Executes all program instructions in the fetch-decode-execute cycle at up to 5.7GHz boost.",
    specs: [
      ["Cores", "16C / 32T"],
      ["Boost", "5.7 GHz"],
      ["TDP", "170W"],
      ["Socket", "AM5"],
    ] as [string, string][],
    fact: "The CPU die is about the size of a fingernail yet contains 13 billion transistors — each one smaller than a coronavirus.",
  },
  gpu: {
    name: "GPU",
    cat: "Processing",
    col: "#6644ff",
    desc: "NVIDIA RTX 4090 — 16,384 CUDA cores, 24GB GDDR6X VRAM. Renders frames into its framebuffer then sends to monitor via HDMI or DisplayPort.",
    specs: [
      ["CUDA cores", "16,384"],
      ["VRAM", "24 GB GDDR6X"],
      ["TDP", "450W"],
      ["Interface", "PCIe 5.0 x16"],
    ] as [string, string][],
    fact: "The RTX 4090 draws 450W — same as a small space heater. Its 16-pin connector can handle up to 600W on a single plug.",
  },
  nvme: {
    name: "NVMe SSD",
    cat: "Storage",
    col: "#00aa44",
    desc: "WD Black SN850X 2TB — connects directly to the CPU via PCIe 4.0 x4. No cable needed — the M.2 slot provides both data and power.",
    specs: [
      ["Interface", "PCIe 4.0 x4"],
      ["Read", "7,300 MB/s"],
      ["Write", "6,600 MB/s"],
      ["Form", "M.2 2280"],
    ] as [string, string][],
    fact: "The same NAND flash chips used in this NVMe drive would be 13x slower in a SATA SSD enclosure — the protocol is the bottleneck.",
  },
  hdd: {
    name: "HDD",
    cat: "Storage",
    col: "#aaaaaa",
    desc: "Seagate Barracuda 8TB — spinning magnetic platters at 7200 RPM. Best cost per GB (~$15/TB) for bulk storage like backups and media.",
    specs: [
      ["Speed", "~200 MB/s"],
      ["RPM", "7,200"],
      ["Capacity", "8 TB"],
      ["Interface", "SATA III"],
    ] as [string, string][],
    fact: "An HDD read arm moves across the platter surface at 60 mph while floating just 3 nanometers above it — thinner than a fingerprint.",
  },
  satassd: {
    name: "SATA SSD",
    cat: "Storage",
    col: "#55aaff",
    desc: 'Samsung 870 EVO 1TB — flash storage in a 2.5" form factor. 4-5x faster than HDD but limited to 550 MB/s by the SATA protocol.',
    specs: [
      ["Read", "~560 MB/s"],
      ["Write", "~530 MB/s"],
      ["Interface", "SATA III"],
      ["Form", '2.5" 7mm'],
    ] as [string, string][],
    fact: "SATA SSDs use the same NAND as NVMe drives but are 13x slower — the bottleneck is the 20-year-old SATA protocol, not the flash chips.",
  },
  psu: {
    name: "PSU",
    cat: "Power",
    col: "#4488ff",
    desc: "750W Gold rated PSU — converts 120/240V AC from the wall into clean DC rails (12V, 5V, 3.3V) for every component.",
    specs: [
      ["Output", "750W"],
      ["Efficiency", "87-90% (Gold)"],
      ["Rails", "12V, 5V, 3.3V"],
      ["Fan", "120mm"],
    ] as [string, string][],
    fact: "At full load a Gold PSU wastes ~10% as heat. At 750W output it draws ~860W from the wall — the extra 110W heats the room.",
  },
  cooler: {
    name: "CPU Cooler",
    cat: "Cooling",
    col: "#cccccc",
    desc: "Noctua NH-D15 dual-tower air cooler — two 140mm fans push air through aluminium fin stacks connected to the CPU by 6 copper heat pipes.",
    specs: [
      ["Type", "Dual-tower air"],
      ["TDP rating", "250W"],
      ["Fans", "2x 140mm PWM"],
      ["Noise", "~24 dB(A)"],
    ] as [string, string][],
    fact: "Heat pipes work by evaporating liquid at the hot CPU end and condensing it at the cool fin end — a passive phase-change loop with no moving parts.",
  },
  monitor: {
    name: "Monitor",
    cat: "Output",
    col: "#1a6aaa",
    desc: "4K 144Hz OLED monitor — receives completed frames from the GPU via HDMI 2.1 or DisplayPort 2.1. Self-emissive pixels give infinite contrast.",
    specs: [
      ["Resolution", "3840×2160"],
      ["Refresh", "144Hz"],
      ["Panel", "OLED"],
      ["Input", "HDMI 2.1 / DP 2.1"],
    ] as [string, string][],
    fact: "At 4K 144Hz the GPU must output 3840×2160×4 bytes×144fps = ~4.8 GB/s of pixel data continuously to keep the display fed.",
  },
  rearIO: {
    name: "Rear I/O",
    cat: "Connectivity",
    col: "#4477cc",
    desc: "The rear I/O panel exposes all board connectivity — USB-A, USB-C, HDMI, DisplayPort, ethernet, and audio jacks directly soldered to the PCB.",
    specs: [
      ["USB", "USB-A 3.2 + USB-C"],
      ["Video", "HDMI 2.1"],
      ["Network", "GbE / 2.5GbE"],
      ["Audio", "3.5mm jacks"],
    ] as [string, string][],
    fact: "The rear I/O shield is pressed steel designed to ground the ports to the case — it prevents ESD damage and reduces RF emissions.",
  },
};
